development:
  adapter: postgresql
  database: phlickr_development
  host: localhost
  username: phil
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: phlickr_test
  host: localhost
  username: phil
  pool: 5
  timeout: 5000